baseURL = 'https://blog.ssyqq.site/'
# languageCode = 'zh-CN'
defaultContentLanguage = "zh-cn"
LanguageCode = "zh-CN"
title = 'LeeeSe'
theme = "LoveIt"


# 默认每页列表显示的文章数目
paginate = 2
# 版权描述，仅仅用于 SEO
copyright = "我是版权"
# 是否使用 robots.txt
enableRobotsTXT = true
# 是否使用 git 信息
enableGitInfo = false
# 是否使用 emoji 代码
enableEmoji = true
hasCJKLanguage = true
# 作者配置
[author]
name = "LeeeSe"
email = "zlsender@163.com"
link = "https://github.com/LeeeSe"
# 菜单配置
[menu]
[[menu.main]]
weight = 1
identifier = "posts"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
name = "文章"
url = "/posts/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
[[menu.main]]
weight = 2
identifier = "tags"
pre = ""
post = ""
name = "标签"
url = "/tags/"
title = ""
[[menu.main]]
weight = 3
identifier = "categories"
pre = ""
post = ""
name = "分类"
url = "/categories/"
title = ""

[params]
# 网站默认主题样式 ["auto", "light", "dark"]
defaultTheme = "auto"
# 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
gitRepo = "https://github.com/LeeeSe/blog"
# LoveIt 新增 | 0.1.1 哪种哈希函数用来 SRI, 为空时表示不使用 SRI
# ["sha256", "sha384", "sha512", "md5"]
fingerprint = ""
# LoveIt 新增 | 0.2.0 日期格式
dateFormat = "2006-01-02"
# 网站标题, 用于 Open Graph 和 Twitter Cards
title = "LeeeSe"
# 网站描述, 用于 RSS, SEO, Open Graph 和 Twitter Cards
description = "这是我的全新 Hugo 网站"
# 网站图片, 用于 Open Graph 和 Twitter Cards
images = ["/logo.png"]
# 页面头部导航栏配置
[params.header]
# 桌面端导航栏模式 ["fixed", "normal", "auto"]
desktopMode = "fixed"
# 移动端导航栏模式 ["fixed", "normal", "auto"]
mobileMode = "auto"
# LoveIt 新增 | 0.2.0 页面头部导航栏标题配置
[params.header.title]
# LOGO 的 URL
logo = ""
# 标题名称
name = "LeeeSe"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
# LoveIt 新增 | 0.2.5 是否为标题显示打字机动画
typeit = false
# 页面底部信息配置
[params.footer]
enable = true
# LoveIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
custom = ''
# LoveIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
hugo = false
# LoveIt 新增 | 0.2.0 是否显示版权信息
copyright = true
# LoveIt 新增 | 0.2.0 是否显示作者
author = true
# 网站创立年份
since = 2022
# ICP 备案信息，仅在中国使用 (支持 HTML 格式)
icp = ""
# 许可协议信息 (支持 HTML 格式)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
# LoveIt 新增 | 0.2.0 Section (所有文章) 页面配置
[params.section]
# section 页面每页显示文章数量
paginate = 5
# 日期格式 (月和日)
dateFormat = "01-02"
# RSS 文章数目
rss = 10

# LoveIt 新增 | 0.2.0 List (目录或标签) 页面配置
[params.list]
# list 页面每页显示文章数量
paginate = 5
# 日期格式 (月和日)
dateFormat = "01-02"
# RSS 文章数目
rss = 10
# LoveIt 新增 | 0.2.0 搜索配置
[params.search]
enable = true
# 搜索引擎的类型 ["lunr", "algolia"]
type = "lunr"
# 文章内容最长索引长度
contentLength = 4000
# 搜索框的占位提示语
placeholder = ""
# LoveIt 新增 | 0.2.1 最大结果数目
maxResultLength = 10
# LoveIt 新增 | 0.2.3 结果内容片段长度
snippetLength = 50
# LoveIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
# LoveIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = true
[params.search.algolia]
index = ""
appID = ""
searchKey = ""
# 主页配置
[params.home]
# LoveIt 新增 | 0.2.0 RSS 文章数目
rss = 10
# 主页个人信息
[params.home.profile]
enable = true
# Gravatar 邮箱，用于优先在主页显示的头像
gravatarEmail = "724818342@qq.com"
# 主页显示头像的 URL
avatarURL = "/images/avatar.png"
# LoveIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
title = "LeeeSe"
# 主页显示的网站副标题 (允许 HTML 格式)
subtitle = "Yearning for a better life and love."
# 是否为副标题显示打字机动画
typeit = false
# 是否显示社交账号
social = true
# LoveIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
disclaimer = ""
# 主页文章列表
[params.home.posts]
enable = true
# 主页每页显示文章数量
paginate = 3

[params.app]
# 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
title = "LeeeSe"
# 是否隐藏网站图标资源链接
noFavicon = false
# 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
svgFavicon = ""
# Android 浏览器主题色
themeColor = "#ffffff"
# Safari 图标颜色
iconColor = "#5bbad5"
# Windows v8-10磁贴颜色
tileColor = "#da532c"

# 作者的社交信息设置
[params.social]
GitHub = "https://github.com/LeeeSe"
Twitter = "https://twitter.com/LeeeSe"
Telegram = "https://t.me/LeeeSe"
Steam = ""
Zhihu = ""
Douban = ""
Mastodon = ""
Discord = ""
Email = "zlsender@163.com"
RSS = false

# LoveIt 更改 | 0.2.0 文章页面全局配置
[params.page]
# LoveIt 新增 | 0.2.0 是否在主页隐藏一篇文章
hiddenFromHomePage = false
# LoveIt 新增 | 0.2.0 是否在搜索结果中隐藏一篇文章
hiddenFromSearch = false
# LoveIt 新增 | 0.2.0 是否使用 twemoji
twemoji = false
# 是否使用 lightgallery
lightgallery = false
# LoveIt 新增 | 0.2.0 是否使用 ruby 扩展语法
ruby = true
# LoveIt 新增 | 0.2.0 是否使用 fraction 扩展语法
fraction = true
# LoveIt 新增 | 0.2.0 是否使用 fontawesome 扩展语法
fontawesome = true
# 是否在文章页面显示原始 Markdown 文档链接
linkToMarkdown = true
# LoveIt 新增 | 0.2.4 是否在 RSS 中显示全文内容
rssFullText = false

# LoveIt 新增 | 0.2.0 目录配置
[params.page.toc]
# 是否使用目录
enable = true
# LoveIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
keepStatic = false
# 是否使侧边目录自动折叠展开
auto = true
# LoveIt 新增 | 0.2.0 代码配置
[params.page.code]
# 是否显示代码块的复制按钮
copy = true
# 默认展开显示的代码行数
maxShownLines = 15
# LoveIt 更改 | 0.2.0 KaTeX 数学公式
[params.page.math]
enable = true
# LoveIt 更改 | 0.2.11 默认行内定界符是 $ ... $ 和 \( ... \)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
# LoveIt 更改 | 0.2.11 默认块定界符是 $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} 和一些其它的函数
blockLeftDelimiter = ""
blockRightDelimiter = ""
# KaTeX 插件 copy_tex
copyTex = true
# KaTeX 插件 mhchem
mhchem = true
# LoveIt 新增 | 0.2.0 Mapbox GL JS 配置
[params.page.mapbox]
# Mapbox GL JS 的 access token
accessToken = ""
# 浅色主题的地图样式
lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
# 深色主题的地图样式
darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
# 是否添加 NavigationControl
navigation = true
# 是否添加 GeolocateControl
geolocate = true
# 是否添加 ScaleControl
scale = true
# 是否添加 FullscreenControl
fullscreen = true

# LoveIt 更改 | 0.2.0 文章页面的分享信息设置
[params.page.share]
enable = true
Twitter = true
Facebook = false
Linkedin = false
Whatsapp = false
Pinterest = false
Tumblr = false
HackerNews = false
Reddit = false
VK = false
Buffer = false
Xing = false
Line = false
Instapaper = false
Pocket = false
Flipboard = false
Weibo = false
Blogger = false
Baidu = false
Odnoklassniki = false
Evernote = false
Skype = false
Trello = false
Mix = false
# LoveIt 更改 | 0.2.0 评论系统设置
[params.page.comment]
enable = true
[params.page.comment.giscus]
# 你可以参考官方文档来使用下列配置
enable = true
repo = "LeeeSe/blog"
repoId = "R_kgDOLPVfrg"
category = "General"
categoryId = "DIC_kwDOLPVfrs4CdBeR"
mapping = "og:title"

[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
